name: static_json_serializable_generator
description: A code generator for serializing static variables of classes.
version: 0.2.1
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/static_json_serializable/static_json_serializable_generator
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.0
  build_config: ^1.1.2
  meta: ^1.11.0
  source_gen: ^4.0.0
  static_json_serializable_annotation: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.15
  build_verify: ^3.1.1
  lints: ^6.0.0
  test: ^1.26.3
