name: markdown_lite
description: A simple package that parses markdown text to an AST.
version: 0.0.0
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/markdown_lite
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
