name: riverpod_state_provider_annotation
description: A package exposing annotations for riverpod_state_provider_generator
version: 2.0.0
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/riverpod_state_provider/riverpod_state_provider_annotation
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues

environment:
  sdk: ^3.3.0

dependencies:
  riverpod_annotation: ^4.0.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
