name: riverpod_state_provider_generator
description: A code generator package for Riverpod's StateProvider.
version: 2.0.0
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/riverpod_state_provider/riverpod_state_provider_generator
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues

environment:
  sdk: ^3.3.0

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.0
  build_config: ^1.1.1
  meta: ^1.11.0
  riverpod_state_provider_annotation: ^2.0.0
  source_gen: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^4.0.0
  riverpod: ^3.0.0
  riverpod_generator: ^4.0.0
  test: ^1.24.0
