name: build_yaml

environment:
  sdk: ^3.3.0

dependencies:
  riverpod_state_provider_annotation: ^2.0.0
  riverpod: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  lints: ^4.0.0
  riverpod_generator: ^4.0.0
  riverpod_state_provider_generator: ^2.0.0
  test: ^1.24.0
