name: markdown_lite_editor
description: A simple markdown editor widget for Flutter.
version: 0.0.0
homepage: https://github.com/ValentinVignal/flutter_packages/tree/main/packages/markdown_lite_editor
repository: https://github.com/ValentinVignal/flutter_packages
issue_tracker: https://github.com/ValentinVignal/flutter_packages/issues

environment:
  sdk: ^3.9.2
  flutter: ">=3.35.6"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  http: ^1.6.0
  markdown_lite: ^0.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
